services:
  bu-adminer:
    image: adminer
    container_name: bu-adminer
    restart: unless-stopped
    ports:
      - 4002:8080
    environment:
      ADMINER_DEFAULT_SERVER: bu-postgres
      ADMINER_DESIGN: pepa-linha-dark
    networks:
      - bu-net
