services:
  bu-postgrest:
    image: postgrest/postgrest:v13.0.4
    container_name: bu-postgrest
    restart: unless-stopped
    networks:
      - bu-net
    ports:
      - 4001:3000
    environment:
      PGRST_DB_URI: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@bu-postgres:5432/budgetbee
      PGRST_DB_SCHEMA: public
      PGRST_DB_POOL: 10
      PGRST_JWT_SECRET: ${PGRST_JWT_SECRET:?environment variable PGRST_JWT_SECRET is not set.}
      PGRST_JWT_AUD: http://localhost:3000
      PGRST_DB_ANON_ROLE: anon
      PGRST_DB_AUTHENTICATED_ROLE: authenticated
    depends_on:
      - bu-postgres


