source ./.env

DB_COMMAND="psql $DATABASE_URL"

if [[ -z "$POSTGRES_SUBSCRIPTION_ADMIN_PASSWORD" ]]; then
    echo "POSTGRES_SUBSCRIPTION_ADMIN_PASSWORD is not set"
    exit 1
fi
$DB_COMMAND -c "CREATE ROLE subscription_admin WITH LOGIN PASSWORD '${POSTGRES_SUBSCRIPTION_ADMIN_PASSWORD}' BYPASSRLS;"

if [[ -z "$POSTGRES_AUTH_ADMIN_PASSWORD" ]]; then
    echo "POSTGRES_AUTH_ADMIN_PASSWORD is not set"
    exit 1
fi
$DB_COMMAND -c "CREATE ROLE auth_admin WITH LOGIN PASSWORD '${POSTGRES_AUTH_ADMIN_PASSWORD}' BYPASSRLS;"
