import { PrismaClient } from "@prisma/client"
import { addDays } from "date-fns"

if (!process.env._DEV_PRISMA_SEED_CLERK_USER_ID)
    throw new Error("Seeding failed. Please provide _DEV_PRISMA_SEED_CLERK_USER_ID env variable")

/**
 * user id of your test clerk user
 * note, that this method does not sync
 * email and other user information, but
 * that is alright
*/
const user_id = process.env._DEV_PRISMA_SEED_CLERK_USER_ID

const prisma = new PrismaClient()

async function main() {
    if (process.env.NODE_ENV === "production") return;

    await prisma.user.create({
        data: {
            id: user_id,
            email: "john.doe@gmail.com",
            username: "john.doe",
            first_name: "John",
            last_name: "Doe"
        }
    })

    await prisma.category.createMany({
        data: ["Food", "Travel", "Rent"].map((name) => ({ name, user_id }))
    })

    await prisma.tag.createMany({
        data: ["good", "expensive", "ok"].map((name) => ({ name, user_id }))
    })

    await prisma.entry.createMany({
        data: (new Array(100)).map(() => ({
            user_id,
            date: addDays(new Date(Date.now()), Math.floor(60 * Math.random() - 30)),
            amount: 1000 * Math.random() - 500, // random number btw -500 and 500
            message: "Autogenerated"
        }))
    })
}

main()
    .then(() => console.log("Seeding successfull"))
    .catch((err) => {
        console.log(err)
        process.exitCode = 1
    })
    .finally(() => prisma.$disconnect())
