#!/usr/bin/env bash

. ./scripts/is_root.sh
. ./scripts/require_envs.sh

only_allow_git_root

source ./.env

require_envs POSTGRES_DATABASE \
    POSTGRES_HOST \
    POSTGRES_PORT \
    POSTGRES_USER \
    POSTGRES_AUTH_ADMIN_USER \
    POSTGRES_SUBSCRIPTION_ADMIN_USER \
    POSTGRES_PASSWORD \
    POSTGRES_AUTH_ADMIN_PASSWORD \
    POSTGRES_SUBSCRIPTION_ADMIN_PASSWORD

DB_URL_ROOT="postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@$POSTGRES_HOST:$POSTGRES_PORT/$POSTGRES_DATABASE"

DB_COMMAND="psql $DB_URL_ROOT"

# Create roles if they don't exist (ignore errors if role already exists)
echo "INFO: Creating role $POSTGRES_SUBSCRIPTION_ADMIN_USER..."
$DB_COMMAND -c "DO \$\$
BEGIN
    CREATE ROLE $POSTGRES_SUBSCRIPTION_ADMIN_USER WITH LOGIN PASSWORD '${POSTGRES_SUBSCRIPTION_ADMIN_PASSWORD}' BYPASSRLS;
EXCEPTION WHEN duplicate_object THEN
    RAISE NOTICE 'Role $POSTGRES_SUBSCRIPTION_ADMIN_USER already exists, skipping.';
END
\$\$;"

echo "INFO: Creating role $POSTGRES_AUTH_ADMIN_USER..."
$DB_COMMAND -c "DO \$\$
BEGIN
    CREATE ROLE $POSTGRES_AUTH_ADMIN_USER WITH LOGIN PASSWORD '${POSTGRES_AUTH_ADMIN_PASSWORD}' BYPASSRLS;
EXCEPTION WHEN duplicate_object THEN
    RAISE NOTICE 'Role $POSTGRES_AUTH_ADMIN_USER already exists, skipping.';
END
\$\$;"

echo "INFO: Role creation complete!"
